name: "Notify result"
inputs: # 呼び出し元から値を受け取れるようにするため変数を定義
  job-title:
    required: true # 必須の変数にするためにrequiredはtrueに
  github-token:
    required: true
runs:
  using: "composite"
  steps:
    # body-includesに指定したコメントを探す
    - name: Find Comment
      uses: peter-evans/find-comment@v1
      id: comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: ${{ inputs.job-title }} results
    # すでに実行結果がコメントされている場合はコメントを削除＆新規作成することで起票者に通知させる
    - uses: actions/github-script@v5
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          if (process.env.COMMENT_ID === '') {
            return;
          }
          github.rest.issues.deleteComment({
            issue_number: ${{ github.event.pull_request.number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: process.env.COMMENT_ID
          })
      env:
        COMMENT_ID: ${{ steps.comment.outputs.comment-id }}
    # job.statusをプルリクエストにコメントする
    - name: ${{ inputs.job-title }} results
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ${{ inputs.job-title }} results: ${{ job.status }}!
        edit-mode: append