name: android unit test

on:
  workflow_dispatch:
jobs:
  android_test:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
          cache: "gradle"
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck
      - name: Publish Test Report
        if: cancelled() != true
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/build/outputs/androidTest-results/*/TEST-*.xml'
      - name: notify result
        if: always()
        uses: ./.github/workflows/composite/notify-result-action
        with:
          job-title: 'Android Unit Test'
          github-token: ${{secrets.GITHUB_TOKEN}}