name: Build Debug APK

on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  build:
    name: Build on merge
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
          cache: "gradle"
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Upload apk file
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Distribute App
        run: |
          curl \
            -H "Authorization: token ${{secrets.DEPLOY_GATE_API_KEY}}" \
            -F "file=@app/build/outputs/apk/debug/app-debug.apk" \
            -F "message=${{github.event.pull_request.title}}" \
            -v "https://deploygate.com/api/users/${{secrets.DEPLOY_GATE_USER_NAME}}/apps"