name: check pr
on:
  pull_request:
    branches:
      - 'master'
      - 'develop'
      - 'feature/**'
      - 'release/**'
jobs:
  android_lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # デフォルトは360分
    strategy:
      matrix:
        ruby: [ '2.7' ]
    steps:
      # 連続でpushした際などは、前回のジョブが残っていたら停止させる
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Cache Gradle
        uses: actions/cache@v2
        id: cache_gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v1
        name: Cache Bundler
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby }}-gems-${{ hashFiles('.github/danger/android_lint.Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ruby }}-gems-
      - name: run android lint
        run: ./gradlew --no-daemon :app:lintDebug
      - uses: MeilCli/danger-action@v5
        if: always()
        name: Run Danger
        with:
          plugins_file: '.github/danger/Gemfile'
          install_path: 'vendor/bundle'
          danger_file: '.github/danger/android_lint.Dangerfile'
          danger_id: 'danger-android-lint'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: notify result
        if: always()
        uses: ./.github/workflows/composite/notify-result-action
        with:
          job-title: 'Android Lint'
          github-token: ${{secrets.GITHUB_TOKEN}}
